### ISSUE TITLE
Relativizar keypoints respecto a keypoint del pecho

### ISSUE THREAD

**Issue by pedroodb** [midusi/LSA-T#3]
Los keypoints ahora están relativizados al centro de la roi (en process_ap.py), debieran estarlo respecto al pecho de la persona

**Comment by pedroodb** [comment]
Que pasa si no tengo un keypoint del pecho con confianza suficiente?

**Comment by facundoq** [comment]
Si son pocos frames,  los estimás con respecto a los valores anteriores y futuros que si superan esa confianza. Ponele algo así:

porcentaje_maximo=0.05
threshold = 0.6
i=0
while i<n_frames:
   if confianza[i]>threshold:
       i++
   else:
        start = i
         while confianza[i]<threshold:
               i++
         end = i
         if (end-start)/n_frames>porcentaje_maximo:
              raise ValueError(f"Cagamos, son un monton  de valores debajo del umbral de confianza")
         keypoints[start:end] = interpolar(keypoints, start,end, window_size)
